project:
  type: website
  output-dir: docs

website:
  title: "DvQ"
  site-url: https://dvquys.com
  description: "DvQ Personal Blog"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - projects.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/dvquy/
      - icon: github
        href: https://github.com/dvquy13
      - icon: twitter-x
        href: https://x.com/dvquys
      - icon: rss
        href: index.xml
  google-analytics: "G-NH6GYY9FZV"
  cookie-consent: true
  favicon: avatar.png

format:
  html:
    theme:
      - united
      - custom.scss
    code-fold: true
    css: styles.css
    mainfont: "InterVariable, Inter, sans-serif"
    highlight-style: github
    fontsize: 15.33px
    linestretch: 1.7
    linkcolor: "#114b8f"
    smooth-scroll: true
    monofont: "Roboto Mono"
    grid:
      # Chosen so that we have maximum 75 characters in the text body for readability
      body-width: 550px
    header-includes: |
      <!-- Inter -->
      <link rel="preconnect" href="https://rsms.me/">
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
      <!-- Roboto Mono -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    anchor-sections: true
    link-external-newwindow: true

toc: true
number-sections: false

resource:
  - CNAME
