---
title: Career Switch
subtitle: How to make a career switch into a technical field?
date: 2024-10-25
categories:
  - life
  - career
keywords: self-taught
layout: full
draft: true
---

## Internal

### Status
- 🧊 Questions
- Wandering
- Organize
- Shorten
- Draft
- Review
- Edit
- Publish

### Objective
- Help readers who is considering career switching be more confident that they can do it
- Help those readers understand what it takes to switch career into a technical field
- Help people understand how I made my career switch

### Questions
- Why do people want to make career switch?
	- What to get out of current state
		- Tired of the current job
	- Interested in a specificed career
		- **Reason** 1: Aspired by the prospects of the new trendy industry
		- Reason 2: Genuinely interested in solving the problems in that area
- What are the blockers that make people less confident?
- In which cases this article would be able to help?
- How did I do it myself?
- What are the key lessons?
	- Start with learning how to learn: pomodoro and spaced repetition
- What does not work?
- When to go full commitment?
- What are the potentially unexpected challenges awaiting you ahead?
- What are the advantages we have?
	- We keep our feet on the ground, always open to learning new things
- How to know if you have reached the crossline—you can safely consider yourself an insider?
- What you should do now after reading this article?

---

Occasionally someone asks me how I made my switch from studying finance to working as an engineer building data science products. I will attempt to give an answer here.

It took me exactly 6 months to transition from a Banking and Finance student at Foreign Trade University to being qualified for a Data Mining Engineer position at Viettel. 

There are three main points:

1. **Persistently build theoretical knowledge:** [Ultimate Learning Path to Becoming a Data Scientist in 2018](https://www.analyticsvidhya.com/blog/2018/01/ultimate-learning-path-becoming-data-scientist-2018/)
2. **Learn and seek application opportunities simultaneously:** Let people around you KNOW you’re looking for problems to solve!
3. **Expand your network, find companions**

Once I decided I wanted to try data, I immediately looked for practical work to see if I really liked it. I chose an internship at a “data-driven” startup in the Business Analytics department. Meanwhile, I read and learned every day. 

During the 3-month BA stint, I used a bit of my prior programming knowledge to solve some operational automation problems. When a newbie codes, they’re bound to hit roadblocks. Whenever stuck, I’d run to the tech room. The guys liked me, saying I was slow but eager to learn. I joined company discussions, shared my views, and indirectly announced I was learning about machine learning.

Luck was on my side. When the company decided to apply machine learning, I was the first to be asked. I got a spot in the tech team, tackled interesting yet basic problems, solved them, got them applied, then moved on to harder ones.

Then, the Entropy 2017 competition by John von Neumann Institute came up. It was perfect timing: I was revisiting Linear Algebra, applying Machine Learning to real problems, and finishing my thesis on Machine Learning. I was eager to see where I stood and meet industry folks. Everything aligned, and I made it to the finals. Top 10, the only non-engineering contestant. Wow, quite exciting.

This competition connected me with several organizations. I got some recognition, and thus, got hired

In conclusion, if you really want it, keep learning, let the world know about you, and stay alert for opportunities.